# Generated by Django 4.2.7 on 2025-05-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpayment',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
