# Generated by Django 4.2.7 on 2025-10-05 10:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('quantity', models.IntegerField(default=0, help_text='Global available stock quantity')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerProductDayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('voiture', models.IntegerField(default=0, help_text="Quantity carried over from yesterday (previous 'retour')")),
                ('sortie', models.IntegerField(default=0, help_text='Quantity newly loaded onto the vehicle today')),
                ('total_loaded', models.IntegerField(default=0, help_text='voiture + sortie')),
                ('retour', models.IntegerField(default=0, help_text='Quantity returned unsold today')),
                ('vendu', models.IntegerField(default=0, help_text='Total sold: (voiture + sortie) - retour')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='vendu * selling_price', max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.seller')),
            ],
            options={
                'verbose_name': 'Daily Inventory Entry',
                'verbose_name_plural': 'Daily Inventory Entries',
                'ordering': ['date', 'seller', 'product'],
                'unique_together': {('seller', 'product', 'date')},
            },
        ),
    ]
