# Generated by Django 4.2.7 on 2025-10-05 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_product_arabic_name'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerproductdayentry',
            options={'verbose_name': 'Entrée Quotidienne Vendeur/Produit', 'verbose_name_plural': 'Entrées Quotidiennes Vendeur/Produit'},
        ),
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='sellerproductdayentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant Vendu'),
        ),
        migrations.AlterField(
            model_name='sellerproductdayentry',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sellerproductdayentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_daily_entries', to='products.product'),
        ),
        migrations.AlterField(
            model_name='sellerproductdayentry',
            name='retour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Retour (Déchargement)'),
        ),
        migrations.AlterField(
            model_name='sellerproductdayentry',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='operations.seller'),
        ),
        migrations.AlterField(
            model_name='sellerproductdayentry',
            name='sortie',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sortie (Chargement)'),
        ),
        migrations.AlterField(
            model_name='sellerproductdayentry',
            name='total_loaded',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Chargé'),
        ),
        migrations.AlterField(
            model_name='sellerproductdayentry',
            name='vendu',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Vendu'),
        ),
        migrations.AlterField(
            model_name='sellerproductdayentry',
            name='voiture',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Stock Précédent (Voiture)'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
