# Generated by Django 4.2.7 on 2025-05-04 10:06

from django.db import migrations, models
import purchases.models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='amount_paid',
        ),
        migrations.AddField(
            model_name='purchase',
            name='due_date',
            field=models.DateField(default=purchases.models.default_due_date),
        ),
    ]
