# Generated by Django 4.2.7 on 2025-05-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_remove_purchase_amount_paid_purchase_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('ordered', 'Commandé'), ('received', 'Reçu'), ('cancelled', 'Annulé')], default='ordered', max_length=20),
        ),
    ]
