# Generated by Django 4.2.7 on 2025-06-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='is_credit',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
