# Generated by Django 4.2.7 on 2025-06-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_is_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='ecriture_generee',
            field=models.BooleanField(default=False),
        ),
    ]
