# Generated by Django 4.2.7 on 2025-06-08 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_stock_reorder_threshold'),
        ('sales', '0004_sale_ecriture_generee'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.warehouse'),
        ),
    ]
