# Generated by Django 4.2.7 on 2025-06-08 20:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_auto_20250608_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricerule',
            options={'ordering': ['-min_quantity']},
        ),
        migrations.AlterUniqueTogether(
            name='pricerule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pricerule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pricerule',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pricegrid',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricerule',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe'), ('fixed_price', 'Prix fixe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pricerule',
            name='price_grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='pricing.pricegrid'),
        ),
    ]
