# Generated by Django 4.2.7 on 2025-06-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_reorder_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arabic_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom en arabe'),
        ),
    ]
