# Generated by Django 4.2.7 on 2025-05-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='alert_threshold',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10, verbose_name="Seuil d'alerte de solde"),
        ),
    ]
